import { useState, useMemo, useEffect, useRef, useCallback } from "react";
import { X, ChevronLeft, ChevronRight, Save, Trash2, RotateCcw, Table, Code, GitCommit, Eye, AlertCircle, Loader2, Check, Sparkles, Settings, Bot, History, Plus, Coins, TreeDeciduous, Clock, Braces, Minimize2, Dices, PenLine, Ban, Hash, Type, Calendar, Link2, CheckCircle2, XCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  Button,
  Input,
  Label,
  ResizeHandle,
  ScrollArea,
  Badge,
  Tooltip,
  TooltipContent,
  TooltipTrigger,
  Switch,
  Textarea,
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DateTimePicker,
  DatePicker,
  TimePicker,
} from "@/components/ui";
import { useUIStore, useCRUDStore, useQueryStore, usePreviewStore, useConnectionsStore, useSchemaStore, selectActiveConnection } from "@/stores";
import { useRedisChangesStore } from "@/stores/redis-changes";
import { useCRUD, useDatabase } from "@/hooks";
import { useRedisCRUD } from "@/hooks/useRedisCRUD";
import { invoke } from "@tauri-apps/api/core";
import type { QueryResult } from "@/types";
import { DiffViewer } from "@/components/data-grid/DiffViewer";
import { DdlPreviewView } from "@/components/preview/DdlPreviewView";
import { DmlPreviewView } from "@/components/preview/DmlPreviewView";
import { useAIStore } from "@/lib/ai/store";
import { useAIAssistant } from "@/lib/ai/hooks";
import { PROVIDER_INFO } from "@/lib/ai/types";
import { ChatMessage } from "@/components/ai/ChatMessage";
import { AIInput } from "@/components/ai/AIInput";
import { AISettingsDialog } from "@/components/ai/AISettingsDialog";
import { ChatHistoryPanel } from "@/components/ai/ChatHistoryPanel";
import { ExplainPanel } from "@/components/explain";
import { SchemaSearchPanel } from "@/components/schema-search";

interface ForeignKeyRef {
  referencesTable: string;
  referencesColumn: string;
}

interface FieldEditorProps {
  name: string;
  value: unknown;
  type: string;
  nullable: boolean;
  isPrimaryKey?: boolean;
  isAutoIncrement?: boolean;
  isCreatingNew?: boolean;
  foreignKey?: ForeignKeyRef;
  connectionId?: string;
  onChange: (value: unknown) => void;
}

// Helper to determine field category from database type
type FieldCategory = "boolean" | "numeric" | "text" | "datetime" | "date" | "time" | "json";

function getFieldCategory(dataType: string): FieldCategory {
  const type = dataType.toLowerCase();

  // Boolean types
  if (type.includes("bool") || type === "bit" || type === "tinyint(1)") {
    return "boolean";
  }

  // Numeric types
  if (
    type.includes("int") ||
    type.includes("decimal") ||
    type.includes("numeric") ||
    type.includes("float") ||
    type.includes("real") ||
    type.includes("double") ||
    type.includes("money") ||
    type.includes("serial") ||
    type === "number"
  ) {
    return "numeric";
  }

  // Time only types (check before datetime/date)
  if (type === "time" || type.startsWith("time ") || type.startsWith("time(")) {
    return "time";
  }

  // Date only types
  if (type === "date") {
    return "date";
  }

  // DateTime/Timestamp types
  if (
    type.includes("datetime") ||
    type.includes("timestamp") ||
    type.includes("interval")
  ) {
    return "datetime";
  }

  // JSON types
  if (type.includes("json") || type.includes("jsonb")) {
    return "json";
  }

  // Default to text
  return "text";
}

// Helper to get icon for field type
function getFieldTypeIcon(category: FieldCategory) {
  switch (category) {
    case "boolean": return null;
    case "numeric": return Hash;
    case "datetime": return Calendar;
    case "date": return Calendar;
    case "time": return Clock;
    case "json": return Braces;
    default: return Type;
  }
}

function FieldEditor({ name, value, type, nullable, isPrimaryKey, isAutoIncrement, isCreatingNew, foreignKey, connectionId, onChange }: FieldEditorProps) {
  const [localValue, setLocalValue] = useState(value);
  const [jsonDialogOpen, setJsonDialogOpen] = useState(false);
  const [jsonDialogValue, setJsonDialogValue] = useState("");
  const [fkValidationState, setFkValidationState] = useState<"idle" | "checking" | "valid" | "invalid">("idle");
  const isNull = localValue === null;
  const fieldCategory = getFieldCategory(type);
  const TypeIcon = getFieldTypeIcon(fieldCategory);
  const isForeignKey = !!foreignKey;

  // Auto-increment fields in create mode should show as "auto-generated"
  const showAutoGenerated = isCreatingNew && isAutoIncrement && isNull;

  // Determine if field should be disabled:
  // - In create mode: only auto-increment fields are disabled (they're auto-generated)
  // - In edit mode: primary keys are disabled (use NULL toggle to enable null fields)
  const isFieldDisabled = isCreatingNew
    ? (isAutoIncrement ?? false)
    : (isPrimaryKey ?? false);

  // For non-nullable fields without auto-increment, user must provide a value
  const isRequired = !nullable && !isAutoIncrement;

  useEffect(() => {
    setLocalValue(value);
    // Reset FK validation when value changes externally
    if (isForeignKey) {
      setFkValidationState("idle");
    }
  }, [value, isForeignKey]);

  const handleChange = (newValue: unknown) => {
    setLocalValue(newValue);
    onChange(newValue);
    // Reset FK validation when value changes
    if (isForeignKey) {
      setFkValidationState("idle");
    }
  };

  // Validate foreign key value exists in referenced table
  const validateForeignKey = async () => {
    if (!foreignKey || !connectionId || isNull || localValue === "" || localValue === undefined) {
      return;
    }

    setFkValidationState("checking");

    try {
      // Build a query to check if the value exists
      const quotedTable = foreignKey.referencesTable;
      const quotedColumn = foreignKey.referencesColumn;
      const valueForQuery = typeof localValue === "string"
        ? `'${String(localValue).replace(/'/g, "''")}'`
        : String(localValue);

      // Use TOP 1 for MSSQL compatibility, most DBs support LIMIT 1 but MSSQL doesn't
      // The backend will handle dialect differences
      const sql = `SELECT 1 AS found FROM ${quotedTable} WHERE ${quotedColumn} = ${valueForQuery}`;

      const result = await invoke<QueryResult>("execute_query", {
        request: { connectionId, sql }
      });

      if (result && result.rows && result.rows.length > 0) {
        setFkValidationState("valid");
      } else {
        setFkValidationState("invalid");
      }
    } catch (error) {
      console.error("FK validation error:", error);
      setFkValidationState("invalid");
    }
  };

  // Convert value to display string
  const getDisplayValue = (): string => {
    if (isNull) return "";
    if (typeof localValue === "boolean") return localValue ? "true" : "false";
    if (typeof localValue === "object") return JSON.stringify(localValue, null, 2);
    return String(localValue);
  };

  // Get default value for enabling a null field
  const getDefaultValue = () => {
    switch (fieldCategory) {
      case "boolean": return false;
      case "numeric": return 0;
      case "datetime":
      case "date":
      case "time":
        return ""; // Empty string so user must select a value
      case "json": return "{}";
      default: return "";
    }
  };

  // Render NULL toggle button - NOW SHOWN FOR ALL NULLABLE FIELDS
  const renderNullButton = () => {
    // Only show NULL button if field is nullable
    if (!nullable) return null;
    // Don't show for auto-increment fields (they're always null/auto)
    if (isAutoIncrement && isCreatingNew) return null;

    return (
      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            variant={isNull ? "secondary" : "outline"}
            size="sm"
            className={cn(
              "shrink-0 h-9 px-2.5 transition-all group/null",
              isNull
                ? "bg-amber-500/15 text-amber-600 dark:text-amber-400 border-amber-500/30 hover:bg-amber-500/25"
                : "text-muted-foreground hover:text-amber-600 dark:hover:text-amber-400 hover:bg-amber-500/10 hover:border-amber-500/30"
            )}
            onClick={() => {
              if (isNull) {
                handleChange(getDefaultValue());
              } else {
                handleChange(null);
              }
            }}
          >
            <Ban className={cn(
              "h-3.5 w-3.5 transition-colors",
              isNull ? "text-amber-600 dark:text-amber-400" : "group-hover/null:text-amber-600 dark:group-hover/null:text-amber-400"
            )} />
          </Button>
        </TooltipTrigger>
        <TooltipContent side="left">
          {isNull ? "Set to value" : "Set to NULL"}
        </TooltipContent>
      </Tooltip>
    );
  };

  // Render FK check button for foreign key fields
  const renderFkCheckButton = () => {
    if (!isForeignKey || !connectionId) return null;
    // Don't show check button if value is null or empty
    if (isNull || localValue === "" || localValue === undefined) return null;

    return (
      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            variant="outline"
            size="sm"
            className={cn(
              "shrink-0 h-9 px-2.5 transition-all",
              fkValidationState === "valid" && "border-success/50 bg-success/10 text-success hover:bg-success/20",
              fkValidationState === "invalid" && "border-destructive/50 bg-destructive/10 text-destructive hover:bg-destructive/20",
              fkValidationState === "checking" && "border-primary/50 bg-primary/10"
            )}
            onClick={validateForeignKey}
            disabled={fkValidationState === "checking"}
          >
            {fkValidationState === "checking" ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : fkValidationState === "valid" ? (
              <CheckCircle2 className="h-3.5 w-3.5" />
            ) : fkValidationState === "invalid" ? (
              <XCircle className="h-3.5 w-3.5" />
            ) : (
              <Link2 className="h-3.5 w-3.5" />
            )}
          </Button>
        </TooltipTrigger>
        <TooltipContent side="left">
          {fkValidationState === "checking" ? "Checking..." :
           fkValidationState === "valid" ? `Found in ${foreignKey!.referencesTable}` :
           fkValidationState === "invalid" ? `Not found in ${foreignKey!.referencesTable}` :
           `Check if exists in ${foreignKey!.referencesTable}`}
        </TooltipContent>
      </Tooltip>
    );
  };

  // Helper: should input be disabled due to null state?
  // Only disable for null if the field is nullable (user can use NULL button to enable)
  // For non-nullable fields with null value (e.g., during insert), allow editing
  const isNullDisabled = isNull && nullable;

  // Render input based on field category
  const renderInput = () => {
    // Boolean: Switch with better visual feedback
    if (fieldCategory === "boolean") {
      const boolValue = localValue === true || localValue === "true" || localValue === 1 || localValue === "1" || localValue === "t";
      return (
        <div className="flex items-center gap-3 flex-1">
          <Switch
            checked={!isNull && boolValue}
            disabled={isFieldDisabled || isNullDisabled}
            onCheckedChange={(checked) => handleChange(checked)}
          />
          <span className={cn(
            "text-sm font-medium tabular-nums",
            isNullDisabled ? "text-amber-600/70 dark:text-amber-400/70 italic" : boolValue ? "text-success" : "text-muted-foreground"
          )}>
            {isNullDisabled ? "NULL" : boolValue ? "true" : "false"}
          </span>
        </div>
      );
    }

    // Numeric: Number input with better formatting
    if (fieldCategory === "numeric") {
      const isInteger = type.toLowerCase().includes("int") || type.toLowerCase().includes("serial");
      return (
        <Input
          type="number"
          step={isInteger ? "1" : "any"}
          value={isNull ? "" : String(localValue)}
          onChange={(e) => {
            const val = e.target.value;
            if (val === "") {
              if (nullable) handleChange(null);
            } else {
              handleChange(isInteger ? parseInt(val, 10) : parseFloat(val));
            }
          }}
          disabled={isFieldDisabled || isNullDisabled}
          className={cn(
            "font-mono text-sm h-9 transition-all flex-1 tabular-nums",
            (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic opacity-70 cursor-not-allowed" : "bg-background/50 focus:bg-background"
          )}
          placeholder={
            isNullDisabled ? "NULL" :
            showAutoGenerated ? "Auto-generated" :
            isInteger ? "0" : "0.00"
          }
        />
      );
    }

    // JSON or long text: Textarea with toolbar
    if (fieldCategory === "json" || (typeof localValue === "string" && localValue.length > 100)) {
      const isJsonField = fieldCategory === "json";

      const prettifyJson = () => {
        try {
          const parsed = typeof localValue === "string" ? JSON.parse(localValue) : localValue;
          const formatted = JSON.stringify(parsed, null, 2);
          handleChange(formatted);
        } catch {
          // Not valid JSON, do nothing
        }
      };

      const minifyJson = () => {
        try {
          const parsed = typeof localValue === "string" ? JSON.parse(localValue) : localValue;
          const minified = JSON.stringify(parsed);
          handleChange(minified);
        } catch {
          // Not valid JSON, do nothing
        }
      };

      const openJsonDialog = () => {
        let displayVal = "";
        if (localValue !== null && localValue !== undefined) {
          if (typeof localValue === "object") {
            displayVal = JSON.stringify(localValue, null, 2);
          } else {
            try {
              displayVal = JSON.stringify(JSON.parse(String(localValue)), null, 2);
            } catch {
              displayVal = String(localValue);
            }
          }
        }
        setJsonDialogValue(displayVal);
        setJsonDialogOpen(true);
      };

      const saveJsonDialog = () => {
        if (isJsonField) {
          try {
            handleChange(JSON.parse(jsonDialogValue));
          } catch {
            handleChange(jsonDialogValue);
          }
        } else {
          handleChange(jsonDialogValue);
        }
        setJsonDialogOpen(false);
      };

      const isValidJson = (() => {
        if (localValue === null || localValue === undefined) return false;
        if (typeof localValue === "object") return true;
        try {
          JSON.parse(String(localValue));
          return true;
        } catch {
          return false;
        }
      })();

      return (
        <>
          <div className="flex-1 space-y-2">
            {isJsonField && (
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1 border border-border rounded-md p-0.5 bg-muted/30">
                  <span className="text-[9px] text-muted-foreground px-1.5 uppercase tracking-wide">Format</span>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 px-2 text-[10px] gap-1"
                        onClick={prettifyJson}
                        disabled={isNull || !isValidJson}
                      >
                        <Braces className="h-3 w-3" />
                        Prettify
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Format JSON with indentation</TooltipContent>
                  </Tooltip>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 px-2 text-[10px] gap-1"
                        onClick={minifyJson}
                        disabled={isNull || !isValidJson}
                      >
                        <Minimize2 className="h-3 w-3" />
                        Minify
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Compact JSON to single line</TooltipContent>
                  </Tooltip>
                </div>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-7 px-2 text-[10px] gap-1"
                      onClick={openJsonDialog}
                      disabled={isFieldDisabled || isNullDisabled}
                    >
                      <PenLine className="h-3 w-3" />
                      Edit
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Open editor dialog</TooltipContent>
                </Tooltip>
              </div>
            )}
            <Textarea
              value={isNull ? "" : getDisplayValue()}
              onChange={(e) => {
                if (isJsonField) {
                  try {
                    handleChange(JSON.parse(e.target.value));
                  } catch {
                    handleChange(e.target.value);
                  }
                } else {
                  handleChange(e.target.value);
                }
              }}
              disabled={isFieldDisabled || isNullDisabled}
              className={cn(
                "font-mono text-xs transition-all min-h-[80px] resize-y",
                (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic" : "bg-background/50 focus:bg-background"
              )}
              placeholder={isNullDisabled ? "NULL" : `Enter ${name}`}
            />
          </div>

          <Dialog open={jsonDialogOpen} onOpenChange={setJsonDialogOpen}>
            <DialogContent className="max-w-2xl max-h-[80vh] flex flex-col">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <Braces className="h-4 w-4" />
                  Edit {name}
                </DialogTitle>
              </DialogHeader>
              <div className="flex-1 min-h-0">
                <Textarea
                  value={jsonDialogValue}
                  onChange={(e) => setJsonDialogValue(e.target.value)}
                  className="font-mono text-xs h-[400px] resize-none"
                  placeholder="Enter JSON or text..."
                />
              </div>
              <DialogFooter className="gap-2">
                {isJsonField && (
                  <>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        try {
                          const parsed = JSON.parse(jsonDialogValue);
                          setJsonDialogValue(JSON.stringify(parsed, null, 2));
                        } catch { /* ignore */ }
                      }}
                    >
                      <Braces className="h-3.5 w-3.5 mr-1.5" />
                      Prettify
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        try {
                          const parsed = JSON.parse(jsonDialogValue);
                          setJsonDialogValue(JSON.stringify(parsed));
                        } catch { /* ignore */ }
                      }}
                    >
                      <Minimize2 className="h-3.5 w-3.5 mr-1.5" />
                      Minify
                    </Button>
                  </>
                )}
                <div className="flex-1" />
                <Button variant="outline" onClick={() => setJsonDialogOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={saveJsonDialog}>
                  <Check className="h-3.5 w-3.5 mr-1.5" />
                  Save
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </>
      );
    }

    // DateTime: Use new DateTimePicker component
    if (fieldCategory === "datetime") {
      return (
        <DateTimePicker
          value={isNull ? null : String(localValue)}
          onChange={(val) => handleChange(val)}
          disabled={isFieldDisabled || isNullDisabled}
          nullable={nullable}
          includeTime={true}
          includeSeconds={true}
          placeholder={isNullDisabled ? "NULL" : "Select date and time..."}
          className={cn(
            "flex-1",
            isNullDisabled && "opacity-70"
          )}
        />
      );
    }

    // Date only: Use DatePicker component
    if (fieldCategory === "date") {
      return (
        <DatePicker
          value={isNull ? null : String(localValue)}
          onChange={(val) => handleChange(val)}
          disabled={isFieldDisabled || isNullDisabled}
          nullable={nullable}
          placeholder={isNullDisabled ? "NULL" : "Select date..."}
          className={cn(
            "flex-1",
            isNullDisabled && "opacity-70"
          )}
        />
      );
    }

    // Time only: Use TimePicker component
    if (fieldCategory === "time") {
      // Extract time portion if full datetime is provided
      const timeValue = (() => {
        if (isNull || !localValue) return null;
        const str = String(localValue);
        // Match HH:MM:SS or HH:MM
        const match = str.match(/(\d{2}):(\d{2})(?::(\d{2}))?/);
        if (match) {
          return match[3] ? `${match[1]}:${match[2]}:${match[3]}` : `${match[1]}:${match[2]}:00`;
        }
        return str;
      })();

      return (
        <TimePicker
          value={timeValue}
          onChange={(val) => handleChange(val)}
          disabled={isFieldDisabled || isNullDisabled}
          nullable={nullable}
          includeSeconds={true}
          placeholder={isNullDisabled ? "NULL" : "Select time..."}
          className={cn(
            "flex-1",
            isNullDisabled && "opacity-70"
          )}
        />
      );
    }

    // UUID: Text input with generate button
    const isUuidField = type.toLowerCase().includes("uuid");
    if (isUuidField) {
      const generateUuid = () => {
        handleChange(crypto.randomUUID());
      };

      return (
        <div className="flex items-center gap-2 flex-1">
          <Input
            type="text"
            value={isNull ? "" : String(localValue)}
            onChange={(e) => handleChange(e.target.value)}
            disabled={isFieldDisabled || isNullDisabled}
            className={cn(
              "font-mono text-sm h-9 transition-all flex-1",
              (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic opacity-70 cursor-not-allowed" : "bg-background/50 focus:bg-background"
            )}
            placeholder={isNullDisabled ? "NULL" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
          />
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="outline"
                size="icon"
                className="h-9 w-9 shrink-0"
                onClick={generateUuid}
                disabled={isFieldDisabled || isNullDisabled}
              >
                <Dices className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>Generate new UUID</TooltipContent>
          </Tooltip>
        </div>
      );
    }

    // Default: Text input
    return (
      <Input
        type="text"
        value={isNull ? "" : getDisplayValue()}
        onChange={(e) => handleChange(e.target.value)}
        disabled={isFieldDisabled || isNullDisabled}
        className={cn(
          "font-mono text-sm h-9 transition-all flex-1",
          (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic opacity-70 cursor-not-allowed" : "bg-background/50 focus:bg-background"
        )}
        placeholder={isNullDisabled ? "NULL" : `Enter ${name}`}
      />
    );
  };

  return (
    <div className={cn(
      "group space-y-2.5 p-3 rounded-lg transition-all border",
      isNullDisabled
        ? "bg-amber-500/5 border-amber-500/20 hover:border-amber-500/30"
        : "border-transparent hover:bg-muted/40 hover:border-border/50"
    )}>
      {/* Header row */}
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2 min-w-0">
          {/* Type icon */}
          {TypeIcon && (
            <TypeIcon className="h-3.5 w-3.5 text-muted-foreground/50 shrink-0" />
          )}
          {/* Field name */}
          <Label className={cn(
            "text-sm font-medium truncate",
            isNullDisabled ? "text-amber-700/80 dark:text-amber-400/80" : "text-foreground/90"
          )}>
            {name}
          </Label>
          {/* Badges */}
          {isPrimaryKey && (
            <Badge variant="outline" className="text-[9px] px-1.5 py-0 h-4 bg-primary/10 text-primary border-primary/30 shrink-0">
              PK
            </Badge>
          )}
          {isAutoIncrement && isCreatingNew && (
            <Badge variant="outline" className="text-[9px] px-1.5 py-0 h-4 bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/30 shrink-0">
              Auto
            </Badge>
          )}
          {isForeignKey && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Badge variant="outline" className="text-[9px] px-1.5 py-0 h-4 bg-violet-500/10 text-violet-600 dark:text-violet-400 border-violet-500/30 shrink-0 cursor-help">
                  <Link2 className="h-2.5 w-2.5 mr-0.5" />
                  FK
                </Badge>
              </TooltipTrigger>
              <TooltipContent side="top" className="text-xs">
                References {foreignKey!.referencesTable}.{foreignKey!.referencesColumn}
              </TooltipContent>
            </Tooltip>
          )}
          {isRequired && isCreatingNew && (
            <span className="text-destructive text-xs font-bold shrink-0" title="Required field">*</span>
          )}
        </div>
        {/* Type badge */}
        <span className={cn(
          "text-[9px] uppercase tracking-wider font-mono px-1.5 py-0.5 rounded border shrink-0",
          isNullDisabled
            ? "text-amber-600/70 dark:text-amber-400/70 bg-amber-500/10 border-amber-500/20"
            : "text-muted-foreground bg-muted/70 border-border/30"
        )}>
          {type}
        </span>
      </div>

      {/* Input row */}
      <div className="flex items-center gap-2">
        {showAutoGenerated ? (
          <div className="flex-1 h-9 px-3 flex items-center bg-muted/50 rounded-md border border-dashed border-blue-500/30 text-sm text-blue-600 dark:text-blue-400 italic">
            <Sparkles className="h-3.5 w-3.5 mr-2 opacity-60" />
            Auto-generated
          </div>
        ) : (
          <>
            {renderInput()}
            {renderFkCheckButton()}
            {renderNullButton()}
          </>
        )}
      </div>
    </div>
  );
}

// Selector for active tab - defined outside component to be stable
const selectActiveTab = (state: { tabs: { id: string; connectionId: string; tableName?: string; title: string }[]; activeTabId: string | null }) => {
  return state.tabs.find(t => t.id === state.activeTabId);
};

// Helper to quote a table identifier (handles schema.table format)
function quoteTableIdentifier(tableName: string, databaseType: string): string {
  const parts = tableName.split('.');
  const quotePart = (part: string) => {
    if (databaseType === 'mysql' || databaseType === 'mariadb') {
      return `\`${part.replace(/`/g, '``')}\``;
    } else if (databaseType === 'mssql') {
      return `[${part.replace(/]/g, ']]')}]`;
    }
    return `"${part.replace(/"/g, '""')}"`;
  };
  return parts.map(quotePart).join('.');
}

// Fields Panel - Row Editor
function FieldsPanel() {
  const {
    selectedRows,
    pendingChanges,
    addPendingChange,
    creatingNewRow,
    updateCreatingRowField,
    cancelCreatingRow,
    saveCreatingRow,
    removeSelectedRow,
    clearSelection,
  } = useCRUDStore();
  const { getSchema } = useSchemaStore();
  const activeTab = useQueryStore(selectActiveTab);
  const [currentRowIndex, setCurrentRowIndex] = useState(0);

  // Check if we're in create mode
  const isCreatingNew = creatingNewRow !== null;

  const currentSelection = selectedRows[currentRowIndex] || selectedRows[0];
  const selectedRowId = currentSelection?.rowId;
  const rowData = isCreatingNew ? creatingNewRow.data : (currentSelection?.rowData || null);
  const rowTableName = isCreatingNew ? creatingNewRow.tableName : (currentSelection?.tableName || "unknown");
  const rowColumns = isCreatingNew ? creatingNewRow.columns : (currentSelection?.columns || []);
  const change = selectedRowId ? pendingChanges[selectedRowId] : null;

  // Get cached schema for better primary key detection
  const connectionId = activeTab?.connectionId;
  const cachedSchema = connectionId ? getSchema(connectionId, rowTableName) : null;

  // Merge columns with cached schema to get accurate isPrimaryKey and dataType
  // The cached schema includes type metadata like IDENTITY/AUTO_INCREMENT markers
  const mergedColumns = useMemo(() => {
    if (!cachedSchema?.columns) return rowColumns;

    // Build maps from cached schema for quick lookup
    const pkSet = new Set(cachedSchema.primaryKeys || []);
    const schemaColMap = new Map(cachedSchema.columns.map(col => [col.name, col]));
    cachedSchema.columns.forEach(col => {
      if (col.isPrimaryKey) pkSet.add(col.name);
    });

    // Merge isPrimaryKey and dataType from cached schema into rowColumns
    return rowColumns.map(col => {
      const schemaCol = schemaColMap.get(col.name);
      return {
        ...col,
        // Use schema dataType if available (includes IDENTITY/AUTO_INCREMENT markers)
        dataType: schemaCol?.dataType || col.dataType,
        isPrimaryKey: col.isPrimaryKey || pkSet.has(col.name),
      };
    });
  }, [rowColumns, cachedSchema]);

  useMemo(() => {
    if (currentRowIndex >= selectedRows.length && selectedRows.length > 0) {
      setCurrentRowIndex(0);
    }
  }, [currentRowIndex, selectedRows.length]);

  // Helper to detect auto-increment columns
  const isAutoIncrementColumn = (dataType: string) => {
    const type = dataType.toLowerCase();
    return (
      type.includes("serial") || // PostgreSQL: serial, bigserial, smallserial
      type.includes("identity") || // MSSQL/Oracle: identity columns
      type.includes("auto_increment") || // MySQL: AUTO_INCREMENT columns
      type.includes("autoincrement") // SQLite: INTEGER PRIMARY KEY AUTOINCREMENT
    );
  };

  // Build FK lookup map from cached schema
  const fkMap = useMemo(() => {
    const map = new Map<string, ForeignKeyRef>();
    if (cachedSchema?.foreignKeys) {
      cachedSchema.foreignKeys.forEach(fk => {
        map.set(fk.column, {
          referencesTable: fk.referencesTable,
          referencesColumn: fk.referencesColumn,
        });
      });
    }
    return map;
  }, [cachedSchema]);

  const fields = mergedColumns.map(col => {
    const isAutoIncrement = isAutoIncrementColumn(col.dataType);
    const foreignKey = fkMap.get(col.name);
    return {
      name: col.name,
      type: col.dataType,
      nullable: col.nullable,
      isPrimaryKey: col.isPrimaryKey,
      isAutoIncrement,
      foreignKey,
      // In create mode, use the creatingNewRow data; otherwise use pending change or original row data
      value: isCreatingNew
        ? creatingNewRow.data[col.name]
        : (change?.newData?.[col.name] ?? rowData?.[col.name])
    };
  });

  const handleFieldChange = (name: string, newValue: unknown) => {
    // In create mode, update the creatingNewRow state
    if (isCreatingNew) {
      updateCreatingRowField(name, newValue);
      return;
    }

    if (!rowData || !mergedColumns.length) return;

    // Use merged columns with accurate isPrimaryKey
    const pkColumns = mergedColumns.filter(c => c.isPrimaryKey).sort((a, b) => a.name.localeCompare(b.name));
    const primaryKey: Record<string, unknown> = {};

    if (pkColumns.length > 0) {
      pkColumns.forEach(c => {
        primaryKey[c.name] = rowData[c.name];
      });
    } else {
      // Fallback: use all columns (but this should rarely happen now)
      const sortedKeys = Object.keys(rowData).sort();
      sortedKeys.forEach(k => {
        primaryKey[k] = rowData[k];
      });
    }

    addPendingChange({
      id: crypto.randomUUID(),
      tableName: rowTableName,
      type: "update",
      originalData: rowData,
      newData: {
        ...(change?.newData || {}),
        [name]: newValue,
      },
      primaryKey,
    });
  };

  // Show empty state only when not creating and no row selected
  if (!isCreatingNew && (!selectedRowId || !rowData)) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-muted-foreground p-8 text-center">
        <div className="relative mb-6">
          <div className="absolute inset-0 bg-primary/5 rounded-full blur-2xl scale-150" />
          <div className="relative bg-gradient-to-br from-muted/80 to-muted/40 p-5 rounded-2xl border border-border/50 shadow-sm">
            <Table className="h-10 w-10 text-muted-foreground/30" />
          </div>
        </div>
        <p className="text-sm font-medium text-foreground/60 mb-2">No row selected</p>
        <p className="text-xs text-muted-foreground/60 max-w-[200px]">
          Click on a row number to select and edit fields
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      {/* Table name indicator */}
      {rowTableName && (
        <div className="flex items-center gap-2 px-4 py-2 border-b border-border bg-muted/30 shrink-0">
          <Table className="h-3.5 w-3.5 text-muted-foreground" />
          <span className="text-xs font-mono text-muted-foreground">{rowTableName}</span>
          {isCreatingNew && (
            <Badge variant="secondary" className="text-[10px] h-5 bg-success/15 text-success border-success/30">
              New Row
            </Badge>
          )}
        </div>
      )}

      {/* Navigation for selection (only when not creating) */}
      {!isCreatingNew && selectedRows.length > 0 && (
        <div className="flex items-center justify-between border-b border-border px-4 py-2 bg-muted/10 shrink-0">
          {selectedRows.length > 1 ? (
            <div className="flex items-center gap-1">
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={() => setCurrentRowIndex(prev => Math.max(0, prev - 1))}
                disabled={currentRowIndex === 0}
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <span className="text-xs font-medium px-2">{currentRowIndex + 1} of {selectedRows.length}</span>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={() => setCurrentRowIndex(prev => Math.min(selectedRows.length - 1, prev + 1))}
                disabled={currentRowIndex === selectedRows.length - 1}
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          ) : (
            <span className="text-xs text-muted-foreground">1 row selected</span>
          )}
          {/* Deselect buttons */}
          <div className="flex items-center gap-1">
            {selectedRows.length > 1 && (
              <Button
                variant="ghost"
                size="sm"
                className="h-7 px-2 text-xs text-muted-foreground hover:text-foreground"
                onClick={() => {
                  const currentRow = selectedRows[currentRowIndex];
                  if (currentRow) {
                    removeSelectedRow(currentRow.rowId);
                    if (currentRowIndex >= selectedRows.length - 1) {
                      setCurrentRowIndex(Math.max(0, currentRowIndex - 1));
                    }
                  }
                }}
                title="Remove current row from selection"
              >
                Remove
              </Button>
            )}
            <Button
              variant="ghost"
              size="sm"
              className="h-7 px-2 text-xs text-muted-foreground hover:text-destructive"
              onClick={clearSelection}
              title="Clear all selection"
            >
              <X className="h-3.5 w-3.5" />
            </Button>
          </div>
        </div>
      )}

      <div className="flex-1 overflow-auto">
        <div className="p-3 space-y-1">
          {fields.map((field) => (
            <FieldEditor
              key={field.name}
              name={field.name}
              value={field.value}
              type={field.type}
              nullable={field.nullable}
              // In create mode, primary keys are editable unless auto-increment
              isPrimaryKey={isCreatingNew ? false : field.isPrimaryKey}
              isAutoIncrement={field.isAutoIncrement}
              isCreatingNew={isCreatingNew}
              foreignKey={field.foreignKey}
              connectionId={connectionId}
              onChange={(newValue) => handleFieldChange(field.name, newValue)}
            />
          ))}
        </div>
      </div>

      {/* Save/Cancel buttons for create mode */}
      {isCreatingNew && (
        <div className="border-t border-border p-3 bg-gradient-to-t from-muted/40 to-muted/20 shrink-0">
          <div className="flex items-center justify-between gap-2">
            <Button
              variant="outline"
              size="sm"
              className="flex-1 text-xs gap-1.5 h-9"
              onClick={cancelCreatingRow}
            >
              <X className="h-3.5 w-3.5" />
              Cancel
            </Button>
            <Button
              size="sm"
              className="flex-1 text-xs gap-1.5 h-9 font-medium shadow-sm bg-success hover:bg-success/90 text-success-foreground"
              onClick={saveCreatingRow}
            >
              <Plus className="h-3.5 w-3.5" />
              Add Row
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

// Helper function to format SQL values for preview
function formatSqlPreviewValue(val: unknown): string {
  if (val === null || val === undefined) {
    return 'NULL';
  }
  if (typeof val === 'boolean') {
    return val ? 'TRUE' : 'FALSE';
  }
  if (typeof val === 'number') {
    return String(val);
  }
  if (typeof val === 'string') {
    return `'${val.replace(/'/g, "''")}'`;
  }
  if (typeof val === 'object') {
    // Handle JSON objects - stringify and escape quotes
    try {
      const jsonStr = JSON.stringify(val);
      return `'${jsonStr.replace(/'/g, "''")}'`;
    } catch {
      return "'[Object]'";
    }
  }
  return `'${String(val)}'`;
}

// Helper function to format WHERE conditions for preview
function formatWhereCondition(key: string, val: unknown): React.ReactNode {
  if (val === null || val === undefined) {
    return (
      <>
        {key} <span className="text-blue-500">IS</span> <span className="text-amber-500">NULL</span>
      </>
    );
  }
  return (
    <>
      {key} = <span className="text-amber-500">{formatSqlPreviewValue(val)}</span>
    </>
  );
}

// Helper to get actual primary key from schema
function useActualPrimaryKey() {
  const { getSchema } = useSchemaStore();
  const activeTab = useQueryStore(selectActiveTab);
  const connectionId = activeTab?.connectionId;

  return useCallback((change: { tableName: string; primaryKey: Record<string, unknown>; originalData?: Record<string, unknown> | null }) => {
    if (!connectionId) return change.primaryKey;

    const cachedSchema = getSchema(connectionId, change.tableName);
    if (!cachedSchema?.columns || !change.originalData) {
      return change.primaryKey;
    }

    // Build set of primary key column names from schema
    const pkSet = new Set(cachedSchema.primaryKeys || []);
    cachedSchema.columns.forEach(col => {
      if (col.isPrimaryKey) pkSet.add(col.name);
    });

    // If schema has primary key info, recalculate from original data
    if (pkSet.size > 0) {
      const actualPK: Record<string, unknown> = {};
      pkSet.forEach(colName => {
        actualPK[colName] = change.originalData![colName];
      });
      return actualPK;
    }

    return change.primaryKey;
  }, [connectionId, getSchema]);
}

// Helper to format a Redis operation as a command preview string
function formatRedisCommandPreview(op: import("@/types").RedisOperation, key: string): React.ReactNode {
  const q = (s: string) => `"${s.replace(/"/g, '\\"')}"`;

  switch (op.op) {
    case "SET":
      return (
        <>
          <span className="text-blue-500">SET</span> <span className="text-amber-500">{q(key)}</span> <span className="text-green-500">{q(op.value)}</span>
        </>
      );
    case "HSET":
      return (
        <>
          <span className="text-blue-500">HSET</span> <span className="text-amber-500">{q(key)}</span> {q(op.field)} <span className="text-green-500">{q(op.value)}</span>
        </>
      );
    case "HDEL":
      return (
        <>
          <span className="text-destructive">HDEL</span> <span className="text-amber-500">{q(key)}</span> {q(op.field)}
        </>
      );
    case "SADD":
      return (
        <>
          <span className="text-blue-500">SADD</span> <span className="text-amber-500">{q(key)}</span> <span className="text-green-500">{q(op.member)}</span>
        </>
      );
    case "SREM":
      return (
        <>
          <span className="text-destructive">SREM</span> <span className="text-amber-500">{q(key)}</span> {q(op.member)}
        </>
      );
    case "ZADD":
      return (
        <>
          <span className="text-blue-500">ZADD</span> <span className="text-amber-500">{q(key)}</span> {op.score} <span className="text-green-500">{q(op.member)}</span>
        </>
      );
    case "ZREM":
      return (
        <>
          <span className="text-destructive">ZREM</span> <span className="text-amber-500">{q(key)}</span> {q(op.member)}
        </>
      );
    case "LSET":
      return (
        <>
          <span className="text-blue-500">LSET</span> <span className="text-amber-500">{q(key)}</span> {op.index} <span className="text-green-500">{q(op.value)}</span>
        </>
      );
    case "RPUSH":
      return (
        <>
          <span className="text-blue-500">RPUSH</span> <span className="text-amber-500">{q(key)}</span> <span className="text-green-500">{q(op.value)}</span>
        </>
      );
    case "LPUSH":
      return (
        <>
          <span className="text-blue-500">LPUSH</span> <span className="text-amber-500">{q(key)}</span> <span className="text-green-500">{q(op.value)}</span>
        </>
      );
    case "LREM":
      return (
        <>
          <span className="text-destructive">LREM</span> <span className="text-amber-500">{q(key)}</span> 1 {q(op.value)}
        </>
      );
  }
}

// Changes Preview Panel
function ChangesPreviewPanel() {
  const {
    pendingChanges,
    removePendingChange,
    clearPendingChanges,
  } = useCRUDStore();
  const { commitChanges } = useCRUD();
  const { executeQuery } = useDatabase();
  const activeTab = useQueryStore(selectActiveTab);
  const { connections } = useConnectionsStore();
  const [viewMode, setViewMode] = useState<"sql" | "diff">("sql");
  const getActualPrimaryKey = useActualPrimaryKey();

  // Redis changes
  const redisPendingChanges = useRedisChangesStore((state) => state.pendingChanges);
  const removeRedisChange = useRedisChangesStore((state) => state.removeChange);
  const clearRedisChanges = useRedisChangesStore((state) => state.clearChanges);
  const { commitRedisChanges } = useRedisCRUD();

  const pendingChangesList = Object.values(pendingChanges);
  const totalChangesCount = pendingChangesList.length + redisPendingChanges.length;

  // Get connection info for quoting identifiers
  const connection = activeTab?.connectionId
    ? connections.find(c => c.id === activeTab.connectionId)
    : null;

  // Commit and refresh data
  const handleCommit = useCallback(async () => {
    // Commit SQL changes
    if (pendingChangesList.length > 0) {
      const successCount = await commitChanges();
      if (successCount && successCount > 0 && activeTab?.connectionId && connection) {
        const tableName = activeTab.tableName || activeTab.title;
        if (tableName) {
          const quotedTable = quoteTableIdentifier(tableName, connection.databaseType);
          await executeQuery(
            {
              connectionId: activeTab.connectionId,
              sql: `SELECT * FROM ${quotedTable}`,
            },
            activeTab.id
          );
        }
      }
    }

    // Commit Redis changes
    if (redisPendingChanges.length > 0) {
      await commitRedisChanges();
    }
  }, [commitChanges, activeTab, connection, executeQuery, redisPendingChanges.length, commitRedisChanges, pendingChangesList.length]);

  // Clear all changes (SQL + Redis)
  const handleClearAll = useCallback(() => {
    clearPendingChanges();
    clearRedisChanges();
  }, [clearPendingChanges, clearRedisChanges]);

  return (
    <div className="flex flex-col h-full">
      {/* View mode toggle */}
      {pendingChangesList.length > 0 && (
        <div className="px-4 py-2 border-b border-border bg-muted/20 shrink-0">
          <div className="flex bg-muted rounded-md p-1 border border-border w-fit">
            <Button
              variant={viewMode === "sql" ? "default" : "ghost"}
              size="sm"
              className={cn(
                "h-7 px-3 text-[11px] gap-1.5 font-medium transition-all",
                viewMode === "sql" && "shadow-sm"
              )}
              onClick={() => setViewMode("sql")}
            >
              <Code className="h-3.5 w-3.5" />
              SQL
            </Button>
            <Button
              variant={viewMode === "diff" ? "default" : "ghost"}
              size="sm"
              className={cn(
                "h-7 px-3 text-[11px] gap-1.5 font-medium transition-all",
                viewMode === "diff" && "shadow-sm"
              )}
              onClick={() => setViewMode("diff")}
            >
              <GitCommit className="h-3.5 w-3.5" />
              Diff
            </Button>
          </div>
        </div>
      )}

      <div className="flex-1 overflow-auto">
        <div className="p-4">
          {viewMode === "sql" ? (
            <div className="font-mono text-xs space-y-4">
              {pendingChangesList.length > 0 && (
                pendingChangesList.map((change, idx) => (
                  <div key={change.id} className="space-y-2 pb-4 border-b border-border last:border-0">
                    <div className="flex items-center justify-between text-[10px] text-muted-foreground mb-1 uppercase tracking-wider">
                      <span>Change #{idx + 1}: {change.type}</span>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-4 w-4 hover:text-destructive"
                        onClick={() => removePendingChange(JSON.stringify(change.primaryKey))}
                      >
                        <Trash2 className="h-3 w-3" />
                      </Button>
                    </div>
                    <div className="bg-muted/50 p-3 rounded border border-border">
                      <pre className="text-foreground whitespace-pre-wrap break-all">
                        {change.type === "insert" && (() => {
                          const insertData = change.newData || {};
                          const columns = Object.keys(insertData);
                          const values = Object.values(insertData);
                          return (
                            <>
                              <span className="text-success">INSERT INTO</span> {change.tableName} <br />
                              <span className="text-muted-foreground">(</span>
                              {columns.map((col, i) => (
                                <span key={col}>
                                  {col}
                                  {i < columns.length - 1 ? ", " : ""}
                                </span>
                              ))}
                              <span className="text-muted-foreground">)</span> <br />
                              <span className="text-blue-500">VALUES</span> <span className="text-muted-foreground">(</span>
                              {values.map((val, i) => (
                                <span key={i}>
                                  <span className="text-amber-500">{formatSqlPreviewValue(val)}</span>
                                  {i < values.length - 1 ? ", " : ""}
                                </span>
                              ))}
                              <span className="text-muted-foreground">)</span>;
                            </>
                          );
                        })()}
                        {change.type === "update" && (() => {
                          const actualPK = getActualPrimaryKey(change);
                          return (
                            <>
                              <span className="text-blue-500">UPDATE</span> {change.tableName} <br />
                              <span className="text-blue-500">SET</span> {
                                Object.entries(change.newData || {}).map(([key, val], i, arr) => (
                                  <span key={key}>
                                    {key} = <span className="text-amber-500">{formatSqlPreviewValue(val)}</span>
                                    {i < arr.length - 1 ? ", " : ""}
                                  </span>
                                ))
                              } <br />
                              <span className="text-blue-500">WHERE</span> {
                                Object.entries(actualPK).map(([key, val], i, arr) => (
                                  <span key={key}>
                                    {formatWhereCondition(key, val)}
                                    {i < arr.length - 1 ? " AND " : ""}
                                  </span>
                                ))
                              };
                            </>
                          );
                        })()}
                        {change.type === "delete" && (() => {
                          const actualPK = getActualPrimaryKey(change);
                          return (
                            <>
                              <span className="text-destructive">DELETE FROM</span> {change.tableName} <br />
                              <span className="text-blue-500">WHERE</span> {
                                Object.entries(actualPK).map(([key, val], i, arr) => (
                                  <span key={key}>
                                    {formatWhereCondition(key, val)}
                                    {i < arr.length - 1 ? " AND " : ""}
                                  </span>
                                ))
                              };
                            </>
                          );
                        })()}
                      </pre>
                    </div>
                  </div>
                ))
              )}

              {/* Redis changes */}
              {redisPendingChanges.length > 0 && (
                <>
                  {pendingChangesList.length > 0 && (
                    <div className="text-[10px] text-muted-foreground uppercase tracking-wider pt-2 pb-1 border-t border-border">
                      Redis Commands
                    </div>
                  )}
                  {redisPendingChanges.map((change) => (
                    <div key={change.id} className="space-y-2 pb-4 border-b border-border last:border-0">
                      <div className="flex items-center justify-between text-[10px] text-muted-foreground mb-1 uppercase tracking-wider">
                        <span className="flex items-center gap-1.5">
                          <span className="px-1 py-0.5 rounded bg-red-500/10 text-red-500 text-[9px] font-semibold normal-case">Redis</span>
                          {change.operation.op}
                        </span>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-4 w-4 hover:text-destructive"
                          onClick={() => removeRedisChange(change.id)}
                        >
                          <Trash2 className="h-3 w-3" />
                        </Button>
                      </div>
                      <div className="bg-muted/50 p-3 rounded border border-border">
                        <pre className="text-foreground whitespace-pre-wrap break-all">
                          {formatRedisCommandPreview(change.operation, change.key)}
                        </pre>
                      </div>
                    </div>
                  ))}
                </>
              )}

              {totalChangesCount === 0 && (
                <div className="flex flex-col items-center justify-center text-muted-foreground p-8 text-center mt-8">
                  <div className="relative mb-6">
                    <div className="absolute inset-0 bg-success/5 rounded-full blur-2xl scale-150" />
                    <div className="relative bg-gradient-to-br from-muted/80 to-muted/40 p-5 rounded-2xl border border-border/50 shadow-sm">
                      <Code className="h-10 w-10 text-muted-foreground/30" />
                    </div>
                  </div>
                  <p className="text-sm font-medium text-foreground/60 mb-2">No pending changes</p>
                  <p className="text-xs text-muted-foreground/60 max-w-[200px]">
                    Edit cell values or Redis keys to see changes here
                  </p>
                </div>
              )}
            </div>
          ) : (
            <DiffViewer changes={pendingChangesList} onRemoveChange={removePendingChange} />
          )}
        </div>
      </div>

      {/* Actions Footer */}
      <div className="border-t border-border p-3 bg-gradient-to-t from-muted/40 to-muted/20 space-y-3 shrink-0">
        <div className="flex items-center justify-between gap-2">
          <Button
            variant="outline"
            size="sm"
            className="flex-1 text-xs gap-1.5 h-9 hover:bg-destructive/10 hover:text-destructive hover:border-destructive/30"
            onClick={handleClearAll}
            disabled={totalChangesCount === 0}
          >
            <RotateCcw className="h-3.5 w-3.5" />
            Clear All
          </Button>
          <Button
            size="sm"
            className={cn(
              "flex-1 text-xs gap-1.5 h-9 font-medium shadow-sm transition-all",
              totalChangesCount > 0
                ? "bg-primary hover:bg-primary/90"
                : "bg-muted text-muted-foreground"
            )}
            disabled={totalChangesCount === 0}
            onClick={handleCommit}
          >
            <Save className="h-3.5 w-3.5" />
            Commit ({totalChangesCount})
          </Button>
        </div>
      </div>
    </div>
  );
}

// Query Preview Panel
function QueryPreviewPanel() {
  const { isPreviewLoading, previewResult, previewSql, previewConnectionId, closePreview } = usePreviewStore();
  const { activeTabId } = useQueryStore();
  const { executeQuery } = useDatabase();

  const hasDdlStatements = useMemo(() => {
    return previewResult?.statements.some((s) => s.statementType === "ddl") ?? false;
  }, [previewResult]);

  const hasDmlStatements = useMemo(() => {
    return previewResult?.statements.some((s) => s.statementType === "dml") ?? false;
  }, [previewResult]);

  const handleApply = async () => {
    if (!previewSql || !previewConnectionId || !activeTabId) return;

    await executeQuery(
      {
        connectionId: previewConnectionId,
        sql: previewSql,
        limit: undefined,
        offset: undefined,
      },
      activeTabId
    );
    closePreview();
  };

  if (!previewResult && !isPreviewLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-muted-foreground p-8 text-center">
        <div className="relative mb-6">
          <div className="absolute inset-0 bg-primary/5 rounded-full blur-2xl scale-150" />
          <div className="relative bg-gradient-to-br from-muted/80 to-muted/40 p-5 rounded-2xl border border-border/50 shadow-sm">
            <Eye className="h-10 w-10 text-muted-foreground/30" />
          </div>
        </div>
        <p className="text-sm font-medium text-foreground/60 mb-2">No preview</p>
        <p className="text-xs text-muted-foreground/60 max-w-[200px]">
          Click "Preview Changes" in a query tab to see DDL/DML preview
        </p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      <div className="flex-1 overflow-auto">
        <div className="p-4">
          {isPreviewLoading ? (
            <div className="flex flex-col items-center justify-center py-16">
              <Loader2 className="h-8 w-8 animate-spin text-primary mb-4" />
              <span className="text-sm text-muted-foreground">Analyzing query...</span>
            </div>
          ) : previewResult?.error ? (
            <div className="flex items-start gap-3 p-4 bg-destructive/10 rounded-lg border border-destructive/20">
              <AlertCircle className="h-5 w-5 text-destructive flex-shrink-0 mt-0.5" />
              <span className="text-sm text-destructive">{previewResult.error}</span>
            </div>
          ) : previewResult ? (
            <div className="space-y-6">
              {previewResult.warning && (
                <div className="flex items-start gap-3 p-4 bg-amber-500/10 rounded-lg border border-amber-500/20">
                  <AlertCircle className="h-5 w-5 text-amber-500 flex-shrink-0 mt-0.5" />
                  <span className="text-sm text-amber-600 dark:text-amber-400">
                    {previewResult.warning}
                  </span>
                </div>
              )}
              {previewResult.success && previewResult.statements.length === 0 && !previewResult.warning && (
                <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
                  <p className="text-sm font-medium text-foreground/60 mb-2">No changes to preview</p>
                  <p className="text-xs text-muted-foreground/60 max-w-[200px] text-center">
                    The query doesn't contain any DDL or DML statements
                  </p>
                </div>
              )}

              {hasDdlStatements && (
                <DdlPreviewView
                  statements={previewResult.statements.filter((s) => s.statementType === "ddl")}
                />
              )}

              {hasDmlStatements && (
                <DmlPreviewView
                  statements={previewResult.statements.filter((s) => s.statementType === "dml")}
                />
              )}

              {previewResult.executionTimeMs > 0 && (
                <div className="text-xs text-muted-foreground text-right pt-2">
                  Preview completed in {previewResult.executionTimeMs}ms
                </div>
              )}
            </div>
          ) : null}
        </div>
      </div>

      {/* Actions Footer */}
      {(previewResult || isPreviewLoading) && (
        <div className="border-t border-border p-3 bg-gradient-to-t from-muted/40 to-muted/20 shrink-0">
          <div className="flex items-center justify-between gap-2">
            <Button
              variant="outline"
              size="sm"
              className="flex-1 text-xs gap-1.5 h-9"
              onClick={closePreview}
            >
              <X className="h-3.5 w-3.5" />
              Cancel
            </Button>
            <Button
              size="sm"
              className="flex-1 text-xs gap-1.5 h-9 font-medium shadow-sm"
              onClick={handleApply}
              disabled={isPreviewLoading || !previewResult?.success}
            >
              <Check className="h-3.5 w-3.5" />
              Apply Changes
            </Button>
          </div>
        </div>
      )}
    </div>
  );
}

// AI Assistant Panel
function AIAssistantPanel() {
  const {
    isConfigured,
    isEnabled,
    isLoading,
    isStreaming,
    messages,
    usageStats,
    sendMessage,
    context,
    updateContext,
  } = useAIAssistant();

  const {
    getCurrentProvider,
    historyPanelOpen,
    setHistoryPanelOpen,
    toggleHistoryPanel,
    getActiveSession,
    createNewChatSession,
  } = useAIStore();

  const activeSession = getActiveSession();

  // Get active connection and its tables
  const activeConnection = useConnectionsStore(selectActiveConnection);
  const tablesByConnection = useQueryStore((state) => state.tablesByConnection);
  const tabs = useQueryStore((state) => state.tabs);
  const activeTabId = useQueryStore((state) => state.activeTabId);

  // Get current query from active tab
  const activeTab = tabs.find(t => t.id === activeTabId);
  const currentQuery = activeTab?.type === "query" ? activeTab.content : undefined;

  const [showSettings, setShowSettings] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const currentProvider = getCurrentProvider();
  const providerDisplayName = PROVIDER_INFO[currentProvider]?.displayName || "AI";

  // Sync tables and current query from active connection to AI context
  useEffect(() => {
    if (activeConnection) {
      const tables = tablesByConnection[activeConnection.id] || [];
      updateContext(tables, undefined, activeConnection.databaseType, activeConnection.id, currentQuery);
    } else {
      updateContext([], undefined, undefined, undefined, undefined);
    }
  }, [activeConnection, tablesByConnection, currentQuery, updateContext]);

  // Auto-scroll to bottom when new messages arrive
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading, isStreaming]);

  if (!isEnabled) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-muted-foreground p-8 text-center">
        <div className="relative mb-6">
          <div className="absolute inset-0 bg-primary/5 rounded-full blur-2xl scale-150" />
          <div className="relative bg-gradient-to-br from-muted/80 to-muted/40 p-5 rounded-2xl border border-border/50 shadow-sm">
            <Sparkles className="h-10 w-10 text-muted-foreground/30" />
          </div>
        </div>
        <p className="text-sm font-medium text-foreground/60 mb-2">AI Disabled</p>
        <p className="text-xs text-muted-foreground/60 max-w-[200px]">
          Enable AI in settings to use the assistant
        </p>
      </div>
    );
  }

  return (
    <div className="relative flex flex-col h-full">
      {/* Header Actions */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-border bg-muted/20 shrink-0">
        <div className="flex items-center gap-2">
          {activeSession && (
            <span className="text-xs text-muted-foreground truncate max-w-[150px]">
              {activeSession.title}
            </span>
          )}
          {usageStats && usageStats.totalTokens > 0 && (
            <Tooltip>
              <TooltipTrigger asChild>
                <span className="flex items-center gap-1 text-[10px] text-violet-400">
                  <Coins className="h-3 w-3" />
                  {usageStats.totalTokens >= 1000
                    ? `${(usageStats.totalTokens / 1000).toFixed(1)}k`
                    : usageStats.totalTokens}
                </span>
              </TooltipTrigger>
              <TooltipContent side="bottom" className="text-xs">
                <div className="space-y-1">
                  <div>Input: {usageStats.totalPromptTokens.toLocaleString()} tokens</div>
                  <div>Output: {usageStats.totalCompletionTokens.toLocaleString()} tokens</div>
                  <div className="font-semibold">Est. cost: ${usageStats.estimatedCost.toFixed(4)}</div>
                </div>
              </TooltipContent>
            </Tooltip>
          )}
        </div>
        <div className="flex items-center gap-0.5">
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={toggleHistoryPanel} title="Chat History">
            <History className="h-3.5 w-3.5" />
          </Button>
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setShowSettings(true)} title="Settings">
            <Settings className="h-3.5 w-3.5" />
          </Button>
          <Button variant="ghost" size="icon" className="h-7 w-7" onClick={createNewChatSession} title="New Chat">
            <Plus className="h-3.5 w-3.5" />
          </Button>
        </div>
      </div>

      {/* Context indicator */}
      {context.selectedTable && (
        <div className="flex items-center gap-2 px-3 py-1.5 bg-muted/30 border-b border-border text-xs shrink-0">
          <span className="text-muted-foreground">Context:</span>
          <Badge variant="secondary" className="text-[10px] h-5">
            {context.selectedTable}
          </Badge>
          {context.databaseType && (
            <Badge variant="outline" className="text-[10px] h-5">
              {context.databaseType}
            </Badge>
          )}
        </div>
      )}

      {/* Messages area */}
      <ScrollArea className="flex-1 overflow-hidden">
        <div className="flex flex-col gap-4 p-3 pb-4 overflow-hidden">
          {!isConfigured && (
            <div className="flex flex-col items-center justify-center gap-3 py-6 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-amber-500/10 text-amber-500">
                <AlertCircle className="h-6 w-6" />
              </div>
              <div>
                <h3 className="font-medium text-sm">API Key Required</h3>
                <p className="text-xs text-muted-foreground mt-1 max-w-[220px]">
                  Configure your {providerDisplayName} API key to use the AI Assistant.
                </p>
              </div>
              <Button variant="default" size="sm" onClick={() => setShowSettings(true)}>
                <Settings className="h-3.5 w-3.5 mr-1.5" />
                Configure
              </Button>
            </div>
          )}

          {isConfigured && messages.length === 0 && (
            <div className="flex flex-col items-center justify-center gap-3 py-6 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-gradient-to-br from-violet-500/20 to-purple-600/20 text-violet-500">
                <Bot className="h-6 w-6" />
              </div>
              <div>
                <h3 className="font-medium text-sm">Ask me about SQL</h3>
                <p className="text-xs text-muted-foreground mt-1 max-w-[220px]">
                  Generate queries, explain SQL, or get optimization tips.
                </p>
              </div>
              <div className="flex flex-wrap gap-1.5 justify-center mt-1">
                {["Show all users", "Count by category"].map((suggestion) => (
                  <Button
                    key={suggestion}
                    variant="outline"
                    size="sm"
                    className="text-[10px] h-6 px-2"
                    onClick={() => sendMessage(suggestion)}
                  >
                    {suggestion}
                  </Button>
                ))}
              </div>
            </div>
          )}

          {messages.map((message) => (
            <ChatMessage key={message.id} message={message} />
          ))}

          {isLoading && !isStreaming && (
            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-muted/50">
              <div className="flex h-6 w-6 items-center justify-center rounded-md bg-gradient-to-br from-violet-500 to-purple-600">
                <Loader2 className="h-3 w-3 text-white animate-spin" />
              </div>
              <span className="text-xs text-muted-foreground">Thinking...</span>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>
      </ScrollArea>

      {/* Input area */}
      <AIInput onSend={sendMessage} isLoading={isLoading} />

      {/* History Panel */}
      <ChatHistoryPanel open={historyPanelOpen} onOpenChange={setHistoryPanelOpen} />

      {/* Settings Dialog */}
      <AISettingsDialog open={showSettings} onOpenChange={setShowSettings} />
    </div>
  );
}

export function SidePanel() {
  const sidePanelOpen = useUIStore(state => state.sidePanelOpen);
  const sidePanelWidth = useUIStore(state => state.sidePanelWidth);
  const setSidePanelWidth = useUIStore(state => state.setSidePanelWidth);
  const rightPanelTab = useUIStore(state => state.rightPanelTab);
  const setRightPanelTab = useUIStore(state => state.setRightPanelTab);
  const selectedRows = useCRUDStore(state => state.selectedRows);
  const pendingChanges = useCRUDStore(state => state.pendingChanges);
  const creatingNewRow = useCRUDStore(state => state.creatingNewRow);

  const pendingChangesList = Object.values(pendingChanges);
  const redisPendingChangesCount = useRedisChangesStore((state) => state.pendingChanges.length);
  const totalPendingCount = pendingChangesList.length + redisPendingChangesCount;

  // Get panel title based on active tab
  const getPanelTitle = () => {
    switch (rightPanelTab) {
      case "fields":
        if (creatingNewRow) return "New Row";
        return selectedRows.length > 1
          ? `${selectedRows.length} Rows Selected`
          : selectedRows.length === 1
            ? "Edit Row"
            : "Fields";
      case "changes":
        return totalPendingCount > 0
          ? `Pending Changes (${totalPendingCount})`
          : "Changes Preview";
      case "preview":
        return "Query Preview";
      case "explain":
        return "Execution Plan";
      case "ai":
        return "AI Assistant";
      default:
        return "Panel";
    }
  };

  // Get panel icon based on active tab
  const getPanelIcon = () => {
    switch (rightPanelTab) {
      case "fields":
        return creatingNewRow ? <Plus className="h-4 w-4" /> : <Table className="h-4 w-4" />;
      case "changes":
        return <Code className="h-4 w-4" />;
      case "preview":
        return <Eye className="h-4 w-4" />;
      case "explain":
        return <TreeDeciduous className="h-4 w-4" />;
      case "ai":
        return <Sparkles className="h-4 w-4" />;
      default:
        return <Table className="h-4 w-4" />;
    }
  };

  if (!sidePanelOpen || !rightPanelTab) {
    return null;
  }

  return (
    <aside
      className={cn(
        "relative flex h-full flex-col border-l border-border bg-card",
        "animate-slide-up"
      )}
      style={{ width: sidePanelWidth }}
    >
      {/* Resize Handle */}
      <ResizeHandle
        direction="left"
        currentWidth={sidePanelWidth}
        onResize={setSidePanelWidth}
        minWidth={280}
        maxWidth={600}
      />

      {/* Header */}
      <div className="flex h-10 items-center justify-between border-b border-border px-3 bg-muted/30 shrink-0">
        <div className="flex items-center gap-2">
          <div className="flex items-center justify-center w-6 h-6 rounded text-primary">
            {getPanelIcon()}
          </div>
          <span className="text-sm font-medium">{getPanelTitle()}</span>
        </div>
        <Button
          variant="ghost"
          size="icon"
          className="h-6 w-6 hover:bg-destructive/10 hover:text-destructive"
          onClick={() => setRightPanelTab(null)}
        >
          <X className="h-3.5 w-3.5" />
        </Button>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-hidden">
        {rightPanelTab === "fields" && <FieldsPanel />}
        {rightPanelTab === "changes" && <ChangesPreviewPanel />}
        {rightPanelTab === "preview" && <QueryPreviewPanel />}
        {rightPanelTab === "explain" && <ExplainPanel />}
        {rightPanelTab === "ai" && <AIAssistantPanel />}
        {rightPanelTab === "schema-search" && <SchemaSearchPanel />}
      </div>
    </aside>
  );
}
