import { useState, useEffect } from "react";
import { Loader2, Check, Sparkles, Clock, Braces, Minimize2, Dices, PenLine, Ban, Hash, Type, Calendar, Link2, CheckCircle2, XCircle } from "lucide-react";
import { cn } from "@/lib/utils";
import {
  Button,
  Input,
  Label,
  Badge,
  Tooltip,
  TooltipContent,
  TooltipTrigger,
  Switch,
  Textarea,
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DateTimePicker,
  DatePicker,
  TimePicker,
} from "@/components/ui";
import { invoke } from "@tauri-apps/api/core";
import type { QueryResult } from "@/types";

export interface ForeignKeyRef {
  referencesTable: string;
  referencesColumn: string;
}

interface FieldEditorProps {
  name: string;
  value: unknown;
  type: string;
  nullable: boolean;
  isPrimaryKey?: boolean;
  isAutoIncrement?: boolean;
  isCreatingNew?: boolean;
  foreignKey?: ForeignKeyRef;
  connectionId?: string;
  onChange: (value: unknown) => void;
}

// Helper to determine field category from database type
type FieldCategory = "boolean" | "numeric" | "text" | "datetime" | "date" | "time" | "json";

function getFieldCategory(dataType: string): FieldCategory {
  const type = dataType.toLowerCase();

  // Boolean types
  if (type.includes("bool") || type === "bit" || type === "tinyint(1)") {
    return "boolean";
  }

  // Numeric types
  if (
    type.includes("int") ||
    type.includes("decimal") ||
    type.includes("numeric") ||
    type.includes("float") ||
    type.includes("real") ||
    type.includes("double") ||
    type.includes("money") ||
    type.includes("serial") ||
    type === "number"
  ) {
    return "numeric";
  }

  // Time only types (check before datetime/date)
  if (type === "time" || type.startsWith("time ") || type.startsWith("time(")) {
    return "time";
  }

  // Date only types
  if (type === "date") {
    return "date";
  }

  // DateTime/Timestamp types
  if (
    type.includes("datetime") ||
    type.includes("timestamp") ||
    type.includes("interval")
  ) {
    return "datetime";
  }

  // JSON types
  if (type.includes("json") || type.includes("jsonb")) {
    return "json";
  }

  // Default to text
  return "text";
}

// Helper to get icon for field type
function getFieldTypeIcon(category: FieldCategory) {
  switch (category) {
    case "boolean": return null;
    case "numeric": return Hash;
    case "datetime": return Calendar;
    case "date": return Calendar;
    case "time": return Clock;
    case "json": return Braces;
    default: return Type;
  }
}

export function FieldEditor({ name, value, type, nullable, isPrimaryKey, isAutoIncrement, isCreatingNew, foreignKey, connectionId, onChange }: FieldEditorProps) {
  const [localValue, setLocalValue] = useState(value);
  const [jsonDialogOpen, setJsonDialogOpen] = useState(false);
  const [jsonDialogValue, setJsonDialogValue] = useState("");
  const [fkValidationState, setFkValidationState] = useState<"idle" | "checking" | "valid" | "invalid">("idle");
  const isNull = localValue === null;
  const fieldCategory = getFieldCategory(type);
  const TypeIcon = getFieldTypeIcon(fieldCategory);
  const isForeignKey = !!foreignKey;

  // Auto-increment fields in create mode should show as "auto-generated"
  const showAutoGenerated = isCreatingNew && isAutoIncrement && isNull;

  // Determine if field should be disabled:
  // - In create mode: only auto-increment fields are disabled (they're auto-generated)
  // - In edit mode: primary keys are disabled (use NULL toggle to enable null fields)
  const isFieldDisabled = isCreatingNew
    ? (isAutoIncrement ?? false)
    : (isPrimaryKey ?? false);

  // For non-nullable fields without auto-increment, user must provide a value
  const isRequired = !nullable && !isAutoIncrement;

  useEffect(() => {
    setLocalValue(value);
    // Reset FK validation when value changes externally
    if (isForeignKey) {
      setFkValidationState("idle");
    }
  }, [value, isForeignKey]);

  const handleChange = (newValue: unknown) => {
    setLocalValue(newValue);
    onChange(newValue);
    // Reset FK validation when value changes
    if (isForeignKey) {
      setFkValidationState("idle");
    }
  };

  // Validate foreign key value exists in referenced table
  const validateForeignKey = async () => {
    if (!foreignKey || !connectionId || isNull || localValue === "" || localValue === undefined) {
      return;
    }

    setFkValidationState("checking");

    try {
      // Build a query to check if the value exists
      const quotedTable = foreignKey.referencesTable;
      const quotedColumn = foreignKey.referencesColumn;
      const valueForQuery = typeof localValue === "string"
        ? `'${String(localValue).replace(/'/g, "''")}'`
        : String(localValue);

      // Use TOP 1 for MSSQL compatibility, most DBs support LIMIT 1 but MSSQL doesn't
      // The backend will handle dialect differences
      const sql = `SELECT 1 AS found FROM ${quotedTable} WHERE ${quotedColumn} = ${valueForQuery}`;

      const result = await invoke<QueryResult>("execute_query", {
        request: { connectionId, sql }
      });

      if (result && result.rows && result.rows.length > 0) {
        setFkValidationState("valid");
      } else {
        setFkValidationState("invalid");
      }
    } catch (error) {
      console.error("FK validation error:", error);
      setFkValidationState("invalid");
    }
  };

  // Convert value to display string
  const getDisplayValue = (): string => {
    if (isNull) return "";
    if (typeof localValue === "boolean") return localValue ? "true" : "false";
    if (typeof localValue === "object") return JSON.stringify(localValue, null, 2);
    return String(localValue);
  };

  // Get default value for enabling a null field
  const getDefaultValue = () => {
    switch (fieldCategory) {
      case "boolean": return false;
      case "numeric": return 0;
      case "datetime":
      case "date":
      case "time":
        return ""; // Empty string so user must select a value
      case "json": return "{}";
      default: return "";
    }
  };

  // Render NULL toggle button - NOW SHOWN FOR ALL NULLABLE FIELDS
  const renderNullButton = () => {
    // Only show NULL button if field is nullable
    if (!nullable) return null;
    // Don't show for auto-increment fields (they're always null/auto)
    if (isAutoIncrement && isCreatingNew) return null;

    return (
      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            variant={isNull ? "secondary" : "outline"}
            size="sm"
            className={cn(
              "shrink-0 h-9 px-2.5 transition-all group/null",
              isNull
                ? "bg-warning/15 text-warning border-warning/30 hover:bg-warning/25"
                : "text-muted-foreground hover:text-warning hover:bg-warning/10 hover:border-warning/30"
            )}
            onClick={() => {
              if (isNull) {
                handleChange(getDefaultValue());
              } else {
                handleChange(null);
              }
            }}
          >
            <Ban className={cn(
              "h-3.5 w-3.5 transition-colors",
              isNull ? "text-warning" : "group-hover/null:text-warning"
            )} />
          </Button>
        </TooltipTrigger>
        <TooltipContent side="left">
          {isNull ? "Set to value" : "Set to NULL"}
        </TooltipContent>
      </Tooltip>
    );
  };

  // Render FK check button for foreign key fields
  const renderFkCheckButton = () => {
    if (!isForeignKey || !connectionId) return null;
    // Don't show check button if value is null or empty
    if (isNull || localValue === "" || localValue === undefined) return null;

    return (
      <Tooltip>
        <TooltipTrigger asChild>
          <Button
            variant="outline"
            size="sm"
            className={cn(
              "shrink-0 h-9 px-2.5 transition-all",
              fkValidationState === "valid" && "border-success/50 bg-success/10 text-success hover:bg-success/20",
              fkValidationState === "invalid" && "border-destructive/50 bg-destructive/10 text-destructive hover:bg-destructive/20",
              fkValidationState === "checking" && "border-primary/50 bg-primary/10"
            )}
            onClick={validateForeignKey}
            disabled={fkValidationState === "checking"}
          >
            {fkValidationState === "checking" ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : fkValidationState === "valid" ? (
              <CheckCircle2 className="h-3.5 w-3.5" />
            ) : fkValidationState === "invalid" ? (
              <XCircle className="h-3.5 w-3.5" />
            ) : (
              <Link2 className="h-3.5 w-3.5" />
            )}
          </Button>
        </TooltipTrigger>
        <TooltipContent side="left">
          {fkValidationState === "checking" ? "Checking..." :
           fkValidationState === "valid" ? `Found in ${foreignKey!.referencesTable}` :
           fkValidationState === "invalid" ? `Not found in ${foreignKey!.referencesTable}` :
           `Check if exists in ${foreignKey!.referencesTable}`}
        </TooltipContent>
      </Tooltip>
    );
  };

  // Helper: should input be disabled due to null state?
  // Only disable for null if the field is nullable (user can use NULL button to enable)
  // For non-nullable fields with null value (e.g., during insert), allow editing
  const isNullDisabled = isNull && nullable;

  // Render input based on field category
  const renderInput = () => {
    // Boolean: Switch with better visual feedback
    if (fieldCategory === "boolean") {
      const boolValue = localValue === true || localValue === "true" || localValue === 1 || localValue === "1" || localValue === "t";
      return (
        <div className="flex items-center gap-3 flex-1">
          <Switch
            checked={!isNull && boolValue}
            disabled={isFieldDisabled || isNullDisabled}
            onCheckedChange={(checked) => handleChange(checked)}
          />
          <span className={cn(
            "text-sm font-medium tabular-nums",
            isNullDisabled ? "text-warning/70 italic" : boolValue ? "text-success" : "text-muted-foreground"
          )}>
            {isNullDisabled ? "NULL" : boolValue ? "true" : "false"}
          </span>
        </div>
      );
    }

    // Numeric: Number input with better formatting
    if (fieldCategory === "numeric") {
      const isInteger = type.toLowerCase().includes("int") || type.toLowerCase().includes("serial");
      return (
        <Input
          type="number"
          step={isInteger ? "1" : "any"}
          value={isNull ? "" : String(localValue)}
          onChange={(e) => {
            const val = e.target.value;
            if (val === "") {
              if (nullable) handleChange(null);
            } else {
              handleChange(isInteger ? parseInt(val, 10) : parseFloat(val));
            }
          }}
          disabled={isFieldDisabled || isNullDisabled}
          className={cn(
            "font-mono text-sm h-9 transition-all flex-1 tabular-nums",
            (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic opacity-70 cursor-not-allowed" : "bg-background/50 focus:bg-background"
          )}
          placeholder={
            isNullDisabled ? "NULL" :
            showAutoGenerated ? "Auto-generated" :
            isInteger ? "0" : "0.00"
          }
        />
      );
    }

    // JSON or long text: Textarea with toolbar
    if (fieldCategory === "json" || (typeof localValue === "string" && localValue.length > 100)) {
      const isJsonField = fieldCategory === "json";

      const prettifyJson = () => {
        try {
          const parsed = typeof localValue === "string" ? JSON.parse(localValue) : localValue;
          const formatted = JSON.stringify(parsed, null, 2);
          handleChange(formatted);
        } catch {
          // Not valid JSON, do nothing
        }
      };

      const minifyJson = () => {
        try {
          const parsed = typeof localValue === "string" ? JSON.parse(localValue) : localValue;
          const minified = JSON.stringify(parsed);
          handleChange(minified);
        } catch {
          // Not valid JSON, do nothing
        }
      };

      const openJsonDialog = () => {
        let displayVal = "";
        if (localValue !== null && localValue !== undefined) {
          if (typeof localValue === "object") {
            displayVal = JSON.stringify(localValue, null, 2);
          } else {
            try {
              displayVal = JSON.stringify(JSON.parse(String(localValue)), null, 2);
            } catch {
              displayVal = String(localValue);
            }
          }
        }
        setJsonDialogValue(displayVal);
        setJsonDialogOpen(true);
      };

      const saveJsonDialog = () => {
        if (isJsonField) {
          try {
            handleChange(JSON.parse(jsonDialogValue));
          } catch {
            handleChange(jsonDialogValue);
          }
        } else {
          handleChange(jsonDialogValue);
        }
        setJsonDialogOpen(false);
      };

      const isValidJson = (() => {
        if (localValue === null || localValue === undefined) return false;
        if (typeof localValue === "object") return true;
        try {
          JSON.parse(String(localValue));
          return true;
        } catch {
          return false;
        }
      })();

      return (
        <>
          <div className="flex-1 space-y-2">
            {isJsonField && (
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1 border border-border rounded-md p-0.5 bg-muted/30">
                  <span className="micro-label px-1.5">Format</span>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 px-2 text-[10px] gap-1"
                        onClick={prettifyJson}
                        disabled={isNull || !isValidJson}
                      >
                        <Braces className="h-3 w-3" />
                        Prettify
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Format JSON with indentation</TooltipContent>
                  </Tooltip>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="h-6 px-2 text-[10px] gap-1"
                        onClick={minifyJson}
                        disabled={isNull || !isValidJson}
                      >
                        <Minimize2 className="h-3 w-3" />
                        Minify
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Compact JSON to single line</TooltipContent>
                  </Tooltip>
                </div>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      className="h-7 px-2 text-[10px] gap-1"
                      onClick={openJsonDialog}
                      disabled={isFieldDisabled || isNullDisabled}
                    >
                      <PenLine className="h-3 w-3" />
                      Edit
                    </Button>
                  </TooltipTrigger>
                  <TooltipContent>Open editor dialog</TooltipContent>
                </Tooltip>
              </div>
            )}
            <Textarea
              value={isNull ? "" : getDisplayValue()}
              onChange={(e) => {
                if (isJsonField) {
                  try {
                    handleChange(JSON.parse(e.target.value));
                  } catch {
                    handleChange(e.target.value);
                  }
                } else {
                  handleChange(e.target.value);
                }
              }}
              disabled={isFieldDisabled || isNullDisabled}
              className={cn(
                "font-mono text-xs transition-all min-h-[80px] resize-y",
                (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic" : "bg-background/50 focus:bg-background"
              )}
              placeholder={isNullDisabled ? "NULL" : `Enter ${name}`}
            />
          </div>

          <Dialog open={jsonDialogOpen} onOpenChange={setJsonDialogOpen}>
            <DialogContent className="max-w-2xl max-h-[80vh] flex flex-col">
              <DialogHeader>
                <DialogTitle className="flex items-center gap-2">
                  <Braces className="h-4 w-4" />
                  Edit {name}
                </DialogTitle>
              </DialogHeader>
              <div className="flex-1 min-h-0">
                <Textarea
                  value={jsonDialogValue}
                  onChange={(e) => setJsonDialogValue(e.target.value)}
                  className="font-mono text-xs h-[400px] resize-none"
                  placeholder="Enter JSON or text..."
                />
              </div>
              <DialogFooter className="gap-2">
                {isJsonField && (
                  <>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        try {
                          const parsed = JSON.parse(jsonDialogValue);
                          setJsonDialogValue(JSON.stringify(parsed, null, 2));
                        } catch { /* ignore */ }
                      }}
                    >
                      <Braces className="h-3.5 w-3.5 mr-1.5" />
                      Prettify
                    </Button>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        try {
                          const parsed = JSON.parse(jsonDialogValue);
                          setJsonDialogValue(JSON.stringify(parsed));
                        } catch { /* ignore */ }
                      }}
                    >
                      <Minimize2 className="h-3.5 w-3.5 mr-1.5" />
                      Minify
                    </Button>
                  </>
                )}
                <div className="flex-1" />
                <Button variant="outline" onClick={() => setJsonDialogOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={saveJsonDialog}>
                  <Check className="h-3.5 w-3.5 mr-1.5" />
                  Save
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </>
      );
    }

    // DateTime: Use new DateTimePicker component
    if (fieldCategory === "datetime") {
      return (
        <DateTimePicker
          value={isNull ? null : String(localValue)}
          onChange={(val) => handleChange(val)}
          disabled={isFieldDisabled || isNullDisabled}
          nullable={nullable}
          includeTime={true}
          includeSeconds={true}
          placeholder={isNullDisabled ? "NULL" : "Select date and time..."}
          className={cn(
            "flex-1",
            isNullDisabled && "opacity-70"
          )}
        />
      );
    }

    // Date only: Use DatePicker component
    if (fieldCategory === "date") {
      return (
        <DatePicker
          value={isNull ? null : String(localValue)}
          onChange={(val) => handleChange(val)}
          disabled={isFieldDisabled || isNullDisabled}
          nullable={nullable}
          placeholder={isNullDisabled ? "NULL" : "Select date..."}
          className={cn(
            "flex-1",
            isNullDisabled && "opacity-70"
          )}
        />
      );
    }

    // Time only: Use TimePicker component
    if (fieldCategory === "time") {
      // Extract time portion if full datetime is provided
      const timeValue = (() => {
        if (isNull || !localValue) return null;
        const str = String(localValue);
        // Match HH:MM:SS or HH:MM
        const match = str.match(/(\d{2}):(\d{2})(?::(\d{2}))?/);
        if (match) {
          return match[3] ? `${match[1]}:${match[2]}:${match[3]}` : `${match[1]}:${match[2]}:00`;
        }
        return str;
      })();

      return (
        <TimePicker
          value={timeValue}
          onChange={(val) => handleChange(val)}
          disabled={isFieldDisabled || isNullDisabled}
          nullable={nullable}
          includeSeconds={true}
          placeholder={isNullDisabled ? "NULL" : "Select time..."}
          className={cn(
            "flex-1",
            isNullDisabled && "opacity-70"
          )}
        />
      );
    }

    // UUID: Text input with generate button
    const isUuidField = type.toLowerCase().includes("uuid");
    if (isUuidField) {
      const generateUuid = () => {
        handleChange(crypto.randomUUID());
      };

      return (
        <div className="flex items-center gap-2 flex-1">
          <Input
            type="text"
            value={isNull ? "" : String(localValue)}
            onChange={(e) => handleChange(e.target.value)}
            disabled={isFieldDisabled || isNullDisabled}
            className={cn(
              "font-mono text-sm h-9 transition-all flex-1",
              (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic opacity-70 cursor-not-allowed" : "bg-background/50 focus:bg-background"
            )}
            placeholder={isNullDisabled ? "NULL" : "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"}
          />
          <Tooltip>
            <TooltipTrigger asChild>
              <Button
                variant="outline"
                size="icon"
                className="h-9 w-9 shrink-0"
                onClick={generateUuid}
                disabled={isFieldDisabled || isNullDisabled}
              >
                <Dices className="h-4 w-4" />
              </Button>
            </TooltipTrigger>
            <TooltipContent>Generate new UUID</TooltipContent>
          </Tooltip>
        </div>
      );
    }

    // Default: Text input
    return (
      <Input
        type="text"
        value={isNull ? "" : getDisplayValue()}
        onChange={(e) => handleChange(e.target.value)}
        disabled={isFieldDisabled || isNullDisabled}
        className={cn(
          "font-mono text-sm h-9 transition-all flex-1",
          (isFieldDisabled || isNullDisabled) ? "bg-muted/50 text-muted-foreground italic opacity-70 cursor-not-allowed" : "bg-background/50 focus:bg-background"
        )}
        placeholder={isNullDisabled ? "NULL" : `Enter ${name}`}
      />
    );
  };

  return (
    <div className={cn(
      "group space-y-2.5 p-3 rounded-lg transition-all border",
      isNullDisabled
        ? "bg-warning/5 border-warning/20 hover:border-warning/30"
        : "border-transparent hover:bg-muted/40 hover:border-border/50"
    )}>
      {/* Header row */}
      <div className="flex items-center justify-between gap-2">
        <div className="flex items-center gap-2 min-w-0">
          {/* Type icon */}
          {TypeIcon && (
            <TypeIcon className="h-3.5 w-3.5 text-muted-foreground/50 shrink-0" />
          )}
          {/* Field name */}
          <Label className={cn(
            "text-sm font-medium truncate",
            isNullDisabled ? "text-warning/80" : "text-foreground/90"
          )}>
            {name}
          </Label>
          {/* Badges */}
          {isPrimaryKey && (
            <Badge variant="outline" className="text-[9px] px-1.5 py-0 h-4 bg-primary/10 text-primary border-primary/30 shrink-0">
              PK
            </Badge>
          )}
          {isAutoIncrement && isCreatingNew && (
            <Badge variant="outline" className="text-[9px] px-1.5 py-0 h-4 bg-info/10 text-info border-info/30 shrink-0">
              Auto
            </Badge>
          )}
          {isForeignKey && (
            <Tooltip>
              <TooltipTrigger asChild>
                <Badge variant="info" className="text-[9px] px-1.5 py-0 h-4 shrink-0 cursor-help">
                  <Link2 className="h-2.5 w-2.5 mr-0.5" />
                  FK
                </Badge>
              </TooltipTrigger>
              <TooltipContent side="top" className="text-xs">
                References {foreignKey!.referencesTable}.{foreignKey!.referencesColumn}
              </TooltipContent>
            </Tooltip>
          )}
          {isRequired && isCreatingNew && (
            <span className="text-destructive text-xs font-bold shrink-0" title="Required field">*</span>
          )}
        </div>
        {/* Type badge */}
        <span className={cn(
          "text-[9px] uppercase tracking-wider font-mono px-1.5 py-0.5 rounded border shrink-0",
          isNullDisabled
            ? "text-warning/70 bg-warning/10 border-warning/20"
            : "text-muted-foreground bg-muted/70 border-border/30"
        )}>
          {type}
        </span>
      </div>

      {/* Input row */}
      <div className="flex items-center gap-2">
        {showAutoGenerated ? (
          <div className="flex-1 h-9 px-3 flex items-center bg-muted/50 rounded-md border border-dashed border-info/30 text-sm text-info italic">
            <Sparkles className="h-3.5 w-3.5 mr-2 opacity-60" />
            Auto-generated
          </div>
        ) : (
          <>
            {renderInput()}
            {renderFkCheckButton()}
            {renderNullButton()}
          </>
        )}
      </div>
    </div>
  );
}
